version: '3'

services:
  frontend:
    build: 
      context: ./frontend
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_BASE_URL: "http://backend:8000/api/v1"

  backend:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
